// Alla boenden med koordinater och info
const accommodations = [
    // TOP KANDIDATER
    {
        id: 1,
        name: "Bastide Saint-Joseph",
        region: "Le Rouret, Frankrike",
        country: "Frankrike",
        lat: 43.6833,
        lng: 7.0167,
        category: "top",
        bedrooms: "?",
        guests: "?",
        pool: "Ja",
        claudeScore: 5,
        chatgptScore: null,
        claudeRank: 1,
        chatgptRank: null,
        byKrav: "Utmärkt - Riktig by med 13 restauranger",
        link: "https://www.booking.com/Share-HpFRjW",
        comment: "Bäst på by-kravet. Provensalsk by med allt på gångavstånd."
    },
    {
        id: 2,
        name: "Villa i Amelia",
        region: "Umbrien, Italien",
        country: "Italien",
        lat: 42.5578,
        lng: 12.4133,
        category: "top",
        bedrooms: 5,
        guests: 14,
        pool: "Privat 16x7m",
        claudeScore: 4,
        chatgptScore: null,
        claudeRank: 2,
        chatgptRank: null,
        byKrav: "Bra - 500m till restaurang, 1km till butik",
        link: "https://www.airbnb.se/rooms/19977255",
        comment: "Betyg 4.96/5. Stor tomt, mountainbikes, stenugn. Längre körväg."
    },
    {
        id: 3,
        name: "Villa Luigi",
        region: "Santo Stefano Belbo, Piemonte",
        country: "Italien",
        lat: 44.7089,
        lng: 8.2322,
        category: "top",
        bedrooms: "5+",
        guests: "10+2",
        pool: "Privat 12x5m",
        claudeScore: 3,
        chatgptScore: 3,
        claudeRank: 3,
        chatgptRank: null,
        byKrav: "Osäkert - Behöver verifieras",
        link: "https://villaluigi-piemonte.com/contact/",
        comment: "Kortast körväg. Nära Alba & Barolo. Kan bli dyrt."
    },
    {
        id: 4,
        name: "Vista dai Colli",
        region: "Venegazzù, Veneto",
        country: "Italien",
        lat: 45.7833,
        lng: 12.0667,
        category: "top",
        bedrooms: 5,
        guests: 14,
        pool: "Privat",
        claudeScore: 3,
        chatgptScore: 5,
        claudeRank: null,
        chatgptRank: 1,
        byKrav: "OK - Liten ort med begränsat utbud",
        link: "https://www.hometogo.se/rental/3de6888a66cfc5152fea829250996ea0",
        comment: "ChatGPTs favorit. Kortast resa + bra hus. Sauna ingår."
    },
    {
        id: 5,
        name: "Villa Cetona",
        region: "Cetona, Toscana",
        country: "Italien",
        lat: 42.9633,
        lng: 11.9017,
        category: "top",
        bedrooms: 5,
        guests: 14,
        pool: "Privat",
        claudeScore: 3,
        chatgptScore: 4,
        claudeRank: null,
        chatgptRank: 2,
        byKrav: "Bra - Cetona är en riktig liten stad",
        link: "https://www.hometogo.se/rental/481829713f1bf3cd",
        comment: "480m². Klassisk Toscana-känsla. By 1-2 km bort."
    },
    {
        id: 6,
        name: "Villa Roccaverano",
        region: "Alta Langa, Piemonte",
        country: "Italien",
        lat: 44.5917,
        lng: 8.2750,
        category: "top",
        bedrooms: 5,
        guests: 12,
        pool: "Infinity",
        claudeScore: 2,
        chatgptScore: 4,
        claudeRank: null,
        chatgptRank: 3,
        byKrav: "OK - Liten by nära",
        link: "https://www.housepiedmont.com/photos",
        comment: "Wow-faktor! 180° utsikt, modern design. Risk för budgetstretch."
    },

    // BRA ALTERNATIV
    {
        id: 7,
        name: "Villa Altura",
        region: "Avigliano Umbro, Umbrien",
        country: "Italien",
        lat: 42.6500,
        lng: 12.4333,
        category: "ok",
        bedrooms: 5,
        guests: 11,
        pool: "Privat",
        claudeScore: 3,
        chatgptScore: 2,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "Medel - 2km till butik/restaurang",
        link: "https://www.airbnb.se/rooms/53714511",
        comment: "Biljardrum, gym, pizzaugn. 11 gäster kan vara tight."
    },
    {
        id: 8,
        name: "Villa Roccaverano (Airbnb)",
        region: "Asti, Piemonte",
        country: "Italien",
        lat: 44.7167,
        lng: 8.1833,
        category: "ok",
        bedrooms: 5,
        guests: 12,
        pool: "Ja",
        claudeScore: 2,
        chatgptScore: null,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "Osäkert - Hilltop, troligen isolerat",
        link: "https://www.airbnb.se/rooms/1385698",
        comment: "Sofia gillade denna. Betyg 4.71/5. Kulle-läge."
    },
    {
        id: 9,
        name: "Novasol Arezzo",
        region: "Arezzo, Toscana",
        country: "Italien",
        lat: 43.4633,
        lng: 11.8797,
        category: "ok",
        bedrooms: 5,
        guests: 12,
        pool: "Ja",
        claudeScore: 2,
        chatgptScore: 2,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "Dåligt - 6km ovanför Arezzo",
        link: "https://www.novasol.se/semesterhus/arezzo-ita731",
        comment: "Definitivt bil-läge. Fin bas."
    },
    {
        id: 10,
        name: "Novasol Barolo",
        region: "Langhe, Piemonte",
        country: "Italien",
        lat: 44.6094,
        lng: 7.9433,
        category: "ok",
        bedrooms: 5,
        guests: 12,
        pool: "Ja",
        claudeScore: 2,
        chatgptScore: null,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "Dåligt - 12km från Barolo",
        link: "https://www.novasol.se/semesterhus/barolo-langhe-ipl128",
        comment: "Bra region men för långt till by."
    },
    {
        id: 11,
        name: "Agriturismo Valtidone Verde",
        region: "Zavattarello, Lombardiet",
        country: "Italien",
        lat: 44.8667,
        lng: 9.2667,
        category: "ok",
        bedrooms: 5,
        guests: 17,
        pool: "Delad",
        claudeScore: 3,
        chatgptScore: 2,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "Isolerat - Bil till allt",
        link: "https://www.hometogo.se/rental/862ba42aa82f0ab0",
        comment: "Störst kapacitet (17 gäster). Organisk gård, härlig utsikt."
    },
    {
        id: 12,
        name: "Villa Mandala Retreat",
        region: "Grognardo, Piemonte",
        country: "Italien",
        lat: 44.6333,
        lng: 8.5167,
        category: "ok",
        bedrooms: "?",
        guests: 12,
        pool: "Ja",
        claudeScore: 2,
        chatgptScore: null,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "Osäkert",
        link: "https://www.booking.com/Share-I9x3Bm",
        comment: "~900 m². Lite över budget."
    },
    {
        id: 13,
        name: "Locanda Di Alberi",
        region: "Borgo San Lorenzo, Toscana",
        country: "Italien",
        lat: 43.9544,
        lng: 11.3878,
        category: "ok",
        bedrooms: 6,
        guests: 14,
        pool: "Privat",
        claudeScore: 2,
        chatgptScore: 3,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "Medel - Landsbygd nära by",
        link: "https://hotels.app.link/jXTuss4Yg0b",
        comment: "Mer B&B-känsla. 23km från Florens."
    },
    {
        id: 14,
        name: "Ca' Seppe",
        region: "Auditore, Marche",
        country: "Italien",
        lat: 43.8167,
        lng: 12.4500,
        category: "ok",
        bedrooms: 4,
        guests: 12,
        pool: "Privat 10x5m",
        claudeScore: 2,
        chatgptScore: 2,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "Isolerat - Avlägset i dalen",
        link: "https://sv.hotels.com/ho3763188224/ca-seppe-10-2-by-marche-holiday-villas/",
        comment: "Fint men fel läge. Nära Urbino."
    },

    // BORT
    {
        id: 15,
        name: "Villa Carra",
        region: "Puglia, Italien",
        country: "Italien",
        lat: 40.0500,
        lng: 18.1167,
        category: "no",
        bedrooms: "?",
        guests: 12,
        pool: "Ja",
        claudeScore: 0,
        chatgptScore: 0,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "-",
        link: "https://hotels.app.link/9ycTj0yZg0b",
        comment: "BORT - För långt söderut (Puglia)"
    },
    {
        id: 16,
        name: "Villa Saturnia",
        region: "Maremma, Toscana",
        country: "Italien",
        lat: 42.6500,
        lng: 11.5167,
        category: "no",
        bedrooms: 6,
        guests: 14,
        pool: "Ja",
        claudeScore: 0,
        chatgptScore: 0,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "-",
        link: "https://rent-tuscany-villas.com/holiday-homes/villa-saturnia",
        comment: "BORT - Bara ledig från 5/7 (fel datum)"
    },
    {
        id: 17,
        name: "La Villa di Primo",
        region: "Cavriglia, Toscana",
        country: "Italien",
        lat: 43.5167,
        lng: 11.4833,
        category: "no",
        bedrooms: 4,
        guests: 8,
        pool: "Privat",
        claudeScore: 0,
        chatgptScore: 0,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "-",
        link: "https://www.airbnb.se/rooms/24418249",
        comment: "BORT - Endast 8 gäster (för litet)"
    },
    {
        id: 18,
        name: "Le Quiete Dimore",
        region: "Pesaro, Marche",
        country: "Italien",
        lat: 43.9100,
        lng: 12.9133,
        category: "no",
        bedrooms: 2,
        guests: 12,
        pool: "Delad",
        claudeScore: 0,
        chatgptScore: 1,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "-",
        link: "https://en.agriturismo.it/rental/23b5a18d778b5d11",
        comment: "BORT - Endast 2 sovrum (för litet)"
    },
    {
        id: 19,
        name: "Novasol Castiglion Fiorentino",
        region: "Castiglion Fiorentino, Toscana",
        country: "Italien",
        lat: 43.3433,
        lng: 11.9217,
        category: "no",
        bedrooms: 5,
        guests: 12,
        pool: "Ja",
        claudeScore: 0,
        chatgptScore: null,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "-",
        link: "https://www.novasol.se/semesterhus/castiglion-fiorentino-ita092",
        comment: "BORT - Beskriven som isolerad bondgård"
    }
];

// Startpunkt (Hjärup)
const startPoint = {
    name: "Hjärup",
    lat: 55.7333,
    lng: 13.1167
};
