// Alla boenden med koordinater och info
const accommodations = [
    // TOP KANDIDATER
    {
        id: 1,
        name: "Bastide Saint-Joseph",
        region: "Le Rouret, Frankrike",
        country: "Frankrike",
        lat: 43.6833,
        lng: 7.0167,
        category: "top",
        bedrooms: 6,
        guests: 12,
        pool: "Ja",
        price: "47 824 kr",
        priceNote: "Deposition €1 000 vid ankomst",
        priceDetails: {
            hyra: "47 824 kr",
            slutstad: "Ingen info",
            sanglinne: "Ingen info",
            turistskatt: "-",
            deposition: "€1 000 vid ankomst (skador)",
            ovrigt: "Aktiviteter mot avgift: vandring, tennis, fiske, kanot"
        },
        yta: "-",
        ac: "Ingen info",
        badrum: 3,
        parkering: "Privat parkering",
        betyg: "9,5/10",
        narmstaOrt: "1 400 m",
        narmstaRestaurang: "1 400 m",
        narmsraShopping: "1 700 m",
        barnaktiviteter: "Lekplats",
        claudeScore: 5,
        chatgptScore: null,
        claudeRank: 1,
        chatgptRank: null,
        byKrav: "Bra - 1,4 km till by, restaurang och shopping",
        link: "https://www.booking.com/Share-HpFRjW",
        comment: "6 sovrum! 1,4 km till by. Lekplats. Många aktiviteter i närheten."
    },
    {
        id: 2,
        name: "Villa i Amelia",
        region: "Umbrien, Italien",
        country: "Italien",
        lat: 42.5578,
        lng: 12.4133,
        category: "top",
        bedrooms: 5,
        guests: 15,
        pool: "Privat 16x7m",
        price: "46 000 kr",
        priceNote: "OBS: Ingen AC!",
        priceDetails: {
            hyra: "46 000 kr",
            slutstad: "Ingår",
            sanglinne: "Ingår",
            turistskatt: "-",
            deposition: "-",
            ovrigt: "El €0,50/kWh + uppvärmning €5/m³. INGEN AC!"
        },
        yta: "160 + 40 m²",
        ac: "NEJ",
        badrum: 5,
        parkering: "Ja",
        betyg: "4,96/5",
        narmstaOrt: "2 000 m (Amelia)",
        narmstaRestaurang: "500 m",
        narmsraShopping: "1 000 m",
        barnaktiviteter: "Bordsfotboll, 5 mountainbikes",
        claudeScore: 4,
        chatgptScore: null,
        claudeRank: 2,
        chatgptRank: null,
        byKrav: "Bra - 500m till restaurang, 1km till butik",
        link: "https://www.airbnb.se/rooms/19977255",
        comment: "15 gäster, 4.96/5. Bordsfotboll, mountainbikes. OBS: Ingen AC!"
    },
    {
        id: 3,
        name: "Villa Luigi",
        region: "Santo Stefano Belbo, Piemonte",
        country: "Italien",
        lat: 44.7089,
        lng: 8.2322,
        category: "top",
        bedrooms: "5+",
        guests: "10+2",
        pool: "Privat 12x5m",
        price: "Förfrågan krävs",
        priceNote: "Kontakta ägaren",
        claudeScore: 3,
        chatgptScore: 3,
        claudeRank: 3,
        chatgptRank: null,
        byKrav: "Osäkert - Behöver verifieras",
        link: "https://villaluigi-piemonte.com/contact/",
        comment: "Kortast körväg. Nära Alba & Barolo. Kan bli dyrt."
    },
    {
        id: 4,
        name: "Vista dai Colli",
        region: "Venegazzù, Veneto",
        country: "Italien",
        lat: 45.7833,
        lng: 12.0667,
        category: "top",
        bedrooms: 5,
        guests: 14,
        pool: "Privat",
        price: "~46 000 kr",
        priceNote: "Hyra 42 000 + städ 4 320 + el",
        priceDetails: {
            hyra: "€3 500 (~42 000 kr)",
            slutstad: "€360 (betalas på plats)",
            sanglinne: "Ingår",
            turistskatt: "Ev. ingen",
            deposition: "Troligen ingen",
            ovrigt: "El tillkommer: ~€0,90/kWh"
        },
        claudeScore: 3,
        chatgptScore: 5,
        claudeRank: null,
        chatgptRank: 1,
        byKrav: "OK - Liten ort med begränsat utbud",
        link: "https://www.hometogo.se/rental/3de6888a66cfc5152fea829250996ea0",
        comment: "ChatGPTs favorit. Kortast resa + bra hus. Sauna ingår. OBS: El tillkommer."
    },
    {
        id: 5,
        name: "Villa Cetona",
        region: "Cetona, Toscana",
        country: "Italien",
        lat: 42.9633,
        lng: 11.9017,
        category: "top",
        bedrooms: 5,
        guests: 14,
        pool: "Privat + jacuzzi",
        price: "~50 400 kr",
        priceNote: "All-inclusive! Städ+linne ingår",
        priceDetails: {
            hyra: "€4 200 (~50 400 kr) all-inclusive",
            slutstad: "Ingår",
            sanglinne: "Ingår (byte 1g/vecka)",
            turistskatt: "€1/pers/natt (≥12 år, kontant)",
            deposition: "Ingen (ZeroDep-försäkring)",
            ovrigt: "El, vatten, gas ingår"
        },
        claudeScore: 3,
        chatgptScore: 4,
        claudeRank: null,
        chatgptRank: 2,
        byKrav: "Bra - Cetona är en riktig liten stad",
        link: "https://www.hometogo.se/rental/481829713f1bf3cd",
        comment: "480m². All-inclusive pris! Städ, linne, el, vatten ingår. Jacuzzi."
    },
    {
        id: 6,
        name: "Villa Roccaverano",
        region: "Alta Langa, Piemonte",
        country: "Italien",
        lat: 44.5917,
        lng: 8.2750,
        category: "no",
        bedrooms: 5,
        guests: 12,
        pool: "Infinity",
        price: "~100 800 kr",
        priceNote: "LÅNGT över budget!",
        priceDetails: {
            hyra: "€8 400 (~100 800 kr) högsäsong",
            slutstad: "Ingår",
            sanglinne: "Ingår",
            turistskatt: "Ev. låg (ej angiven)",
            deposition: "€1 500 (återbetalas, via kort)",
            ovrigt: "All service ingår"
        },
        claudeScore: 2,
        chatgptScore: 4,
        claudeRank: null,
        chatgptRank: 3,
        byKrav: "OK - Liten by nära",
        link: "https://www.housepiedmont.com/photos",
        comment: "BORT - 100 800 kr! Dubbla budgeten. Wow-hus men orealistiskt pris."
    },

    // BRA ALTERNATIV
    {
        id: 7,
        name: "Villa Altura",
        region: "Avigliano Umbro, Umbrien",
        country: "Italien",
        lat: 42.6500,
        lng: 12.4333,
        category: "ok",
        bedrooms: 5,
        guests: 11,
        pool: "Privat",
        price: "~44 000 kr",
        priceNote: "$625/natt på Airbnb",
        claudeScore: 3,
        chatgptScore: 2,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "Medel - 2km till butik/restaurang",
        link: "https://www.airbnb.se/rooms/53714511",
        comment: "Biljardrum, gym, pizzaugn. 11 gäster kan vara tight."
    },
    {
        id: 8,
        name: "Villa Roccaverano (Airbnb)",
        region: "Asti, Piemonte",
        country: "Italien",
        lat: 44.7167,
        lng: 8.1833,
        category: "ok",
        bedrooms: 5,
        guests: 12,
        pool: "Ja",
        price: "~42 000 kr",
        priceNote: "$603/natt på Airbnb",
        claudeScore: 2,
        chatgptScore: null,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "Osäkert - Hilltop, troligen isolerat",
        link: "https://www.airbnb.se/rooms/1385698",
        comment: "Sofia gillade denna. Betyg 4.71/5. Kulle-läge."
    },
    {
        id: 9,
        name: "Novasol Arezzo",
        region: "Arezzo, Toscana",
        country: "Italien",
        lat: 43.4633,
        lng: 11.8797,
        category: "ok",
        bedrooms: 5,
        guests: 12,
        pool: "Ja (32 m²)",
        price: "47 945 kr",
        priceNote: "Turistskatt 33 kr/dag/pers",
        priceDetails: {
            hyra: "47 945 kr",
            slutstad: "Ingår",
            sanglinne: "Ingår",
            turistskatt: "32,61 kr/dag/person",
            deposition: "-",
            ovrigt: "AC, diskmaskin, grill, bordtennis, dart, gunga, rutschkana, fotbollsmål"
        },
        yta: "420 m²",
        ac: "Ja",
        badrum: 4,
        parkering: "4 st",
        betyg: "5/5",
        narmstaOrt: "6 000 m (Arezzo)",
        narmstaRestaurang: "700 m",
        narmsraShopping: "4 500 m",
        barnaktiviteter: "Bordtennis, dart, gunga, rutschkana, fotbollsmål, badminton, volleyboll",
        claudeScore: 2,
        chatgptScore: 2,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "Medel - Restaurang 700m men shopping 4,5km",
        link: "https://www.novasol.se/semesterhus/arezzo-ita731",
        comment: "420m², 5/5 betyg! Massor av barnaktiviteter. Restaurang 700m. Shopping långt."
    },
    {
        id: 10,
        name: "Novasol Barolo",
        region: "Langhe, Piemonte",
        country: "Italien",
        lat: 44.6094,
        lng: 7.9433,
        category: "ok",
        bedrooms: 6,
        guests: 12,
        pool: "Ja (50 m²)",
        price: "26 688 kr",
        priceNote: "Billigast! Men el+gas extra",
        priceDetails: {
            hyra: "26 688 kr",
            slutstad: "Ingår",
            sanglinne: "-",
            turistskatt: "-",
            deposition: "3 261 kr",
            ovrigt: "El 3,80 kr/kWh + gas 59,78 kr/m³. Sänglinne ingår EJ!"
        },
        yta: "350 m²",
        ac: "Ja",
        badrum: 3,
        parkering: "2 st",
        betyg: "4,4/5",
        narmstaOrt: "12 000 m (Barolo)",
        narmstaRestaurang: "800 m",
        narmsraShopping: "800 m",
        barnaktiviteter: "Gunga, rutschkana, leksaker ute + inne",
        claudeScore: 2,
        chatgptScore: null,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "OK - Restaurang & shopping 800m! Men 12km till Barolo",
        link: "https://www.novasol.se/semesterhus/barolo-langhe-ipl128",
        comment: "BILLIGAST: 26 688 kr! 6 sovrum, 350m², pool 50m². Men sänglinne ingår ej, el+gas extra."
    },
    {
        id: 11,
        name: "Agriturismo Valtidone Verde",
        region: "Zavattarello, Lombardiet",
        country: "Italien",
        lat: 44.8667,
        lng: 9.2667,
        category: "ok",
        bedrooms: 5,
        guests: 17,
        pool: "Delad",
        price: "~47 600 kr",
        priceNote: "Från HomeToGo",
        claudeScore: 3,
        chatgptScore: 2,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "Isolerat - Bil till allt",
        link: "https://www.hometogo.se/rental/862ba42aa82f0ab0",
        comment: "Störst kapacitet (17 gäster). Organisk gård, härlig utsikt."
    },
    {
        id: 12,
        name: "Villa Mandala Retreat",
        region: "Grognardo, Piemonte",
        country: "Italien",
        lat: 44.6333,
        lng: 8.5167,
        category: "ok",
        bedrooms: "?",
        guests: 12,
        pool: "Ja",
        price: "Över budget",
        priceNote: "~900 m², dyrt",
        claudeScore: 2,
        chatgptScore: null,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "Osäkert",
        link: "https://www.booking.com/Share-I9x3Bm",
        comment: "~900 m². Lite över budget."
    },
    {
        id: 13,
        name: "Locanda Di Alberi",
        region: "Borgo San Lorenzo, Toscana",
        country: "Italien",
        lat: 43.9544,
        lng: 11.3878,
        category: "ok",
        bedrooms: 6,
        guests: 14,
        pool: "Privat",
        price: "50 696 kr",
        priceNote: "Frukost ingår! Daglig städning",
        priceDetails: {
            hyra: "50 696 kr",
            slutstad: "Daglig städning ingår",
            sanglinne: "Ingår",
            turistskatt: "€1/pers/natt (ej barn)",
            deposition: "€500 (enbart skador)",
            ovrigt: "Frukost ingår! Kök mot extraavgift. Uppvärmning 30€/natt/boende (säsong)"
        },
        yta: "-",
        ac: "-",
        badrum: 6,
        parkering: "Gatupark + område",
        betyg: "9,2/10",
        narmstaOrt: "-",
        narmstaRestaurang: "8 min med bil",
        narmsraShopping: "-",
        barnaktiviteter: "Spel. OBS: Uteplatser/balkonger EJ barnvänliga!",
        claudeScore: 2,
        chatgptScore: 3,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "Dåligt - Restaurang 8 min med bil",
        link: "https://hotels.app.link/jXTuss4Yg0b",
        comment: "Frukost + daglig städning! Men: kök kostar extra, bil till restaurang, balkonger ej barnvänliga."
    },
    {
        id: 14,
        name: "Ca' Seppe",
        region: "Auditore, Marche",
        country: "Italien",
        lat: 43.8167,
        lng: 12.4500,
        category: "ok",
        bedrooms: 4,
        guests: 12,
        pool: "Privat",
        price: "51 569 kr",
        priceNote: "Snåriga vägar!",
        priceDetails: {
            hyra: "51 569 kr",
            slutstad: "Ingår",
            sanglinne: "Ingår",
            turistskatt: "-",
            deposition: "-",
            ovrigt: "OBS: Snåriga vägar upp till villan"
        },
        yta: "380 m²",
        ac: "Nej",
        badrum: 3,
        parkering: "Gatuparkering",
        betyg: "-",
        narmstaOrt: "-",
        narmstaRestaurang: "18 min med bil",
        narmsraShopping: "-",
        barnaktiviteter: "-",
        claudeScore: 2,
        chatgptScore: 2,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "Dåligt - 18 min bil till restaurang, snåriga vägar",
        link: "https://sv.hotels.com/ho3763188224/ca-seppe-10-2-by-marche-holiday-villas/",
        comment: "51 569 kr. Snåriga vägar, 18 min bil till restaurang, ingen AC. Nära Urbino."
    },

    // BORT
    {
        id: 15,
        name: "Villa Carra",
        region: "Puglia, Italien",
        country: "Italien",
        lat: 40.0500,
        lng: 18.1167,
        category: "no",
        bedrooms: "?",
        guests: 12,
        pool: "Ja",
        claudeScore: 0,
        chatgptScore: 0,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "-",
        link: "https://hotels.app.link/9ycTj0yZg0b",
        comment: "BORT - För långt söderut (Puglia)"
    },
    {
        id: 16,
        name: "Villa Saturnia",
        region: "Maremma, Toscana",
        country: "Italien",
        lat: 42.6500,
        lng: 11.5167,
        category: "no",
        bedrooms: 6,
        guests: 14,
        pool: "Ja",
        claudeScore: 0,
        chatgptScore: 0,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "-",
        link: "https://rent-tuscany-villas.com/holiday-homes/villa-saturnia",
        comment: "BORT - Bara ledig från 5/7 (fel datum)"
    },
    {
        id: 17,
        name: "La Villa di Primo",
        region: "Cavriglia, Toscana",
        country: "Italien",
        lat: 43.5167,
        lng: 11.4833,
        category: "no",
        bedrooms: 4,
        guests: 8,
        pool: "Privat",
        claudeScore: 0,
        chatgptScore: 0,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "-",
        link: "https://www.airbnb.se/rooms/24418249",
        comment: "BORT - Endast 8 gäster (för litet)"
    },
    {
        id: 18,
        name: "Le Quiete Dimore",
        region: "Pesaro, Marche",
        country: "Italien",
        lat: 43.9100,
        lng: 12.9133,
        category: "no",
        bedrooms: 2,
        guests: 12,
        pool: "Delad",
        claudeScore: 0,
        chatgptScore: 1,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "-",
        link: "https://en.agriturismo.it/rental/23b5a18d778b5d11",
        comment: "BORT - Endast 2 sovrum (för litet)"
    },
    {
        id: 19,
        name: "Novasol Castiglion Fiorentino",
        region: "Castiglion Fiorentino, Toscana",
        country: "Italien",
        lat: 43.3433,
        lng: 11.9217,
        category: "no",
        bedrooms: 5,
        guests: 12,
        pool: "Ja",
        claudeScore: 0,
        chatgptScore: null,
        claudeRank: null,
        chatgptRank: null,
        byKrav: "-",
        link: "https://www.novasol.se/semesterhus/castiglion-fiorentino-ita092",
        comment: "BORT - Beskriven som isolerad bondgård"
    }
];

// Startpunkt (Hjärup)
const startPoint = {
    name: "Hjärup",
    lat: 55.7333,
    lng: 13.1167
};
